services:
  rest_api:
    build: ./rest_api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./rest_api/swagger.yml:/app/swagger.yml  # Ajout du fichier Swagger
      - ./rest_api:/app  # Ajout pour s'assurer que les fichiers sont bien copiés

  grpc_service:
    build: ./grpc_service
    ports:
      - "50051:50051"
    volumes:
      - ./data:/app/data
      - ./grpc_service:/app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - rest_api
      - grpc_service
