swagger: "2.0"
info:
  title: "EgaPro API"
  description: "API pour récupérer les données de l'index Égalité FH"
  version: "1.0.0"
schemes:
  - http
 
paths:
  /api/v1/entreprises:
    get:
      summary: "Récupérer la liste des entreprises"
      responses:
        200:
          description: "Liste des entreprises"
          schema:
            type: array
            items:
              type: object
              properties:
                siren:
                  type: string
                name:
                  type: string
